name = "forge-modpack"
author = "BattleCh1cken"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aad56a7080a7ed4de7f757541c037fdb99de353b09695ca57e0c0f96bd0c5310"

[versions]
forge = "40.1.84"
minecraft = "1.18.2"
